# Shell variables
# Generated by 'wal'
wallpaper='/home/albedo/dotfiles/home/Pictures/wallpapers/arch-chan_to.png'

# Special
background='#030207'
foreground='#f4def6'
cursor='#f4def6'

# Colors
color0='#030207'
color1='#6253B8'
color2='#4776B7'
color3='#956EE7'
color4='#A2A0A4'
color5='#AB8FFC'
color6='#DCAAFE'
color7='#f4def6'
color8='#aa9bac'
color9='#6253B8'
color10='#4776B7'
color11='#956EE7'
color12='#A2A0A4'
color13='#AB8FFC'
color14='#DCAAFE'
color15='#f4def6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
