--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/albedo/dotfiles/home/Pictures/wallpapers/arch-chan_to.png"

-- Special
background="#030207"
foreground="#f4def6"
cursor="#f4def6"

-- Colors
color0="#030207"
color1="#6253B8"
color2="#4776B7"
color3="#956EE7"
color4="#A2A0A4"
color5="#AB8FFC"
color6="#DCAAFE"
color7="#f4def6"
color8="#aa9bac"
color9="#6253B8"
color10="#4776B7"
color11="#956EE7"
color12="#A2A0A4"
color13="#AB8FFC"
color14="#DCAAFE"
color15="#f4def6"
