--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/albedo/dotfiles/home/Pictures/wallpapers/anime-girl-abyss.png"

-- Special
background="#020A12"
foreground="#e9c8cb"
cursor="#e9c8cb"

-- Colors
color0="#020A12"
color1="#9D2A35"
color2="#C15253"
color3="#E39373"
color4="#36738C"
color5="#B0788F"
color6="#2EA7B3"
color7="#e9c8cb"
color8="#a38c8e"
color9="#9D2A35"
color10="#C15253"
color11="#E39373"
color12="#36738C"
color13="#B0788F"
color14="#2EA7B3"
color15="#e9c8cb"
