# Shell variables
# Generated by 'wal'
wallpaper='/home/albedo/dotfiles/home/Pictures/wallpapers/anime-girl-abyss.png'

# Special
background='#020A12'
foreground='#e9c8cb'
cursor='#e9c8cb'

# Colors
color0='#020A12'
color1='#9D2A35'
color2='#C15253'
color3='#E39373'
color4='#36738C'
color5='#B0788F'
color6='#2EA7B3'
color7='#e9c8cb'
color8='#a38c8e'
color9='#9D2A35'
color10='#C15253'
color11='#E39373'
color12='#36738C'
color13='#B0788F'
color14='#2EA7B3'
color15='#e9c8cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
