# Shell variables
# Generated by 'wal'
wallpaper='/home/albedo/dotfiles/home/Pictures/wallpapers/night_anime.jpg'

# Special
background='#090a0c'
foreground='#9eaabc'
cursor='#9eaabc'

# Colors
color0='#090a0c'
color1='#384358'
color2='#3A4E6A'
color3='#4C4F61'
color4='#3D5E85'
color5='#3F6187'
color6='#4F6689'
color7='#9eaabc'
color8='#6e7683'
color9='#384358'
color10='#3A4E6A'
color11='#4C4F61'
color12='#3D5E85'
color13='#3F6187'
color14='#4F6689'
color15='#9eaabc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
